name: invitations_project
description: "Invitations project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  dartz: ^0.10.1
  email_validator: ^3.0.0
  flutter_bloc: ^8.1.6
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  injectable: ^2.5.0
  mockito: ^5.4.5
  uuid: ^4.5.1
  equatable: ^2.0.7
  provider: ^6.1.2
  cloud_firestore: ^5.6.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  mocktail: ^1.0.4
  auth_buttons: ^3.0.3
  google_sign_in: ^6.2.2
  in_app_purchase: ^3.2.0
  firebase_analytics: ^11.3.6
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2
  sign_in_with_apple: ^6.1.4
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1
  google_sign_in_mocks: ^0.3.0
  mock_exceptions: ^0.8.2

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  auto_route_generator: ^9.0.0

  flutter_lints: ^5.0.0
  lints: ^5.1.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
