name: invitations_project
description: "Invitations project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  dartz: ^0.10.1
  email_validator: ^3.0.0
  flutter_bloc: ^8.1.6
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  injectable: ^2.5.0
  mockito: ^5.4.4
  uuid: ^4.5.1
  equatable: ^2.0.7
  provider: ^6.1.2
  cloud_firestore: ^5.5.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  auto_route_generator: ^9.0.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
