name: invitations_project
description: "Invitations project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  auth_buttons: ^3.0.3
  auto_route: ^10.0.1
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  email_validator: ^3.0.0
  equatable: ^2.0.7
  fake_cloud_firestore: ^3.1.0
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  firebase_auth_mocks: ^0.14.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_stripe: ^11.4.0
  flutter_stripe_web: ^6.4.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_sign_in: ^6.3.0
  google_sign_in_mocks: ^0.3.0
  hydrated_bloc: ^10.0.0
  image_picker: ^1.1.2
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mock_exceptions: ^0.8.2
  mockito: ^5.4.5
  mocktail: ^1.0.4
  path_provider: ^2.1.5
  provider: ^6.1.2
  sign_in_with_apple: ^6.1.4
  uuid: ^4.5.1
  very_good_analysis: ^7.0.0

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  lints: ^5.1.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
